//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Att_Tem_DASR
    {
        public decimal AutoId { get; set; }
        public string EmployeeID { get; set; }
        public string DepartmentCode { get; set; }
        public string LineCode { get; set; }
        public string DesignationCode { get; set; }
        public string AttStatus { get; set; }
    }
}
