//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attd_Temp_DailyInOut_Voyager
    {
        public decimal AutoId { get; set; }
        public string EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string DesignationName { get; set; }
        public string DepartmentName { get; set; }
        public string DepartmentCode { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string InTime { get; set; }
        public string OutTime { get; set; }
        public string OnDuty { get; set; }
        public string OffDuty { get; set; }
        public string Overtime { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
    }
}
