//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttMainData
    {
        public decimal AutoId { get; set; }
        public string EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string DesignationName { get; set; }
        public string DepartmentName { get; set; }
        public string SectionName { get; set; }
        public string DepartmentCode { get; set; }
        public string LineName { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> InTime { get; set; }
        public Nullable<System.DateTime> OutTime { get; set; }
        public Nullable<System.DateTime> SDIntime { get; set; }
        public Nullable<System.DateTime> SDLateTime { get; set; }
        public Nullable<System.DateTime> SDOutTime { get; set; }
        public Nullable<System.DateTime> OutTime_br { get; set; }
        public string AttStatus { get; set; }
        public string OTTimeBr { get; set; }
        public string HMSIn24hc { get; set; }
        public string HMIN12hc { get; set; }
        public string HMIN24hc { get; set; }
        public string HIn12hc { get; set; }
        public string MIn12hc { get; set; }
        public string Mod_MIn12hc { get; set; }
        public string Mod_SIn12hc { get; set; }
        public string AMPM { get; set; }
        public string AttendanceTypeCode { get; set; }
        public string EmpTypeCode { get; set; }
        public string ShiftCode { get; set; }
        public string OUTMOD { get; set; }
        public string ISDDEmpty { get; set; }
        public Nullable<System.DateTime> ND_MD_MinDT { get; set; }
        public Nullable<System.DateTime> ND_DD_MinDT { get; set; }
    }
}
