//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_Def_Currency
    {
        public decimal TC { get; set; }
        public string CurrencyId { get; set; }
        public string CurrencyName { get; set; }
        public string ShortName { get; set; }
        public string Symbol { get; set; }
        public Nullable<int> DecimalPlaces { get; set; }
        public string NegativeFormat { get; set; }
        public string LUser { get; set; }
        public Nullable<System.DateTime> LDate { get; set; }
        public string LIP { get; set; }
        public string LMAC { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    }
}
