//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_AccessCode2
    {
        public int AccessID { get; set; }
        public string AccessCodeID { get; set; }
        public string AccessCodeName { get; set; }
        public string TitleCheck { get; set; }
        public string title { get; set; }
        public string PageUrl { get; set; }
        public string chkAdd { get; set; }
        public string chkEdit { get; set; }
        public string chkDelete { get; set; }
        public string chkPrint { get; set; }
        public string ParentID { get; set; }
        public string MenuId { get; set; }
        public string OrderBy { get; set; }
        public string MenuText { get; set; }
        public string ControllerName { get; set; }
        public string ViewName { get; set; }
        public string Icon { get; set; }
    }
}
