//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_UserInfo2
    {
        public int ID { get; set; }
        public string username { get; set; }
        public string AccessCode { get; set; }
        public string EmployeeID { get; set; }
        public string Role { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string LUser { get; set; }
        public Nullable<System.DateTime> LDate { get; set; }
        public string LIP { get; set; }
        public string LMAC { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string UserPassword { get; set; }
    }
}
