//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_AccessCode
    {
        public int AccessID { get; set; }
        public string AccessCode { get; set; }
        public Nullable<int> id { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string title { get; set; }
        public string url { get; set; }
        public string Status { get; set; }
        public string OPStatus { get; set; }
        public Nullable<int> MenuOrder { get; set; }
        public Nullable<bool> chkAdd { get; set; }
        public Nullable<bool> chkUpdate { get; set; }
        public Nullable<bool> chkDelete { get; set; }
        public Nullable<bool> chkClear { get; set; }
        public Nullable<bool> chkPrint { get; set; }
        public string AccessDesc { get; set; }
    }
}
