//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_Country
    {
        public int CountryCode { get; set; }
        public string CountryID { get; set; }
        public string CountryName { get; set; }
        public string IOCCode { get; set; }
        public string ISOCode { get; set; }
        public Nullable<System.DateTime> LDate { get; set; }
        public string LUser { get; set; }
        public string LIP { get; set; }
        public string LMAC { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    }
}
