//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_MenuTab
    {
        public int id { get; set; }
        public Nullable<int> parentID { get; set; }
        public string title { get; set; }
        public Nullable<int> Status { get; set; }
        public string url { get; set; }
        public string OPStatus { get; set; }
        public Nullable<int> MenuOrder { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public Nullable<int> GridOrder { get; set; }
    }
}
