//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_Favorate
    {
        public int FavID { get; set; }
        public Nullable<int> PageID { get; set; }
        public string username { get; set; }
        public Nullable<int> Position { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> LDate { get; set; }
        public string LUser { get; set; }
        public string LIP { get; set; }
        public string LMAC { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    
        public virtual Core_Favorate Core_Favorate1 { get; set; }
        public virtual Core_Favorate Core_Favorate2 { get; set; }
    }
}
