//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_Attd_Temp_DASR_Email
    {
        public decimal AutoId { get; set; }
        public string DepartmentName { get; set; }
        public string LineName { get; set; }
        public string DesignationName { get; set; }
        public int Present { get; set; }
        public int Late { get; set; }
        public int Absent { get; set; }
        public int Strength { get; set; }
        public int DeviceAccessedEmployee { get; set; }
        public int DeviceNoAccessedEmployee { get; set; }
        public string DivisionName { get; set; }
        public string AttStatus { get; set; }
        public string InTime { get; set; }
        public string Sick { get; set; }
    }
}
