//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_PAY_OTRuleSetup
    {
        public decimal OvertimeRuleCode { get; set; }
        public string OvertimeRuleId { get; set; }
        public int OTMaxPerDay { get; set; }
        public string CalculationTypeId { get; set; }
        public int MultiplyWith { get; set; }
        public int OTMaxPerMonth { get; set; }
        public System.DateTime WEF { get; set; }
        public string Remarks { get; set; }
        public string LUser { get; set; }
        public Nullable<System.DateTime> LDate { get; set; }
        public string LIP { get; set; }
        public string LMAC { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    }
}
