//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_Attd_TimeCalculation2_TBSC_F2
    {
        public decimal autoId { get; set; }
        public string FingerPrintID { get; set; }
        public System.TimeSpan TotalTime { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan SalaryTranTime { get; set; }
        public decimal StayInOffice_Hours { get; set; }
        public decimal SalaryHours { get; set; }
        public decimal SalaryAmount { get; set; }
        public System.TimeSpan OT { get; set; }
        public System.TimeSpan OTInSS { get; set; }
    }
}
