//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_EmployeeDailyMovementInfo
    {
        public decimal autoId { get; set; }
        public string empMovmentID { get; set; }
        public string EmployeeID { get; set; }
        public string MainCompanyID { get; set; }
        public string BranchID { get; set; }
        public string DivisionID { get; set; }
        public string CustomerID { get; set; }
        public string DestinationFromID { get; set; }
        public string DestinationToID { get; set; }
        public Nullable<System.DateTime> MovementDate { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public string VehicleTypeID { get; set; }
        public string NotifyTypeID { get; set; }
        public Nullable<decimal> ConveyanceAmount { get; set; }
        public string LUser { get; set; }
        public Nullable<System.DateTime> LDate { get; set; }
        public string LIP { get; set; }
        public string LMAC { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string UserInfoEmployeeID { get; set; }
        public string CompanyCode { get; set; }
        public string OtherTypeID { get; set; }
    }
}
