//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_EmployeeMedicalInfo
    {
        public decimal autoId { get; set; }
        public string EmpMedicalInfoCode { get; set; }
        public string EmployeeCode { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public string HealthCard { get; set; }
        public string Disease { get; set; }
        public string Allergies { get; set; }
        public string Operation { get; set; }
        public decimal LimitAnount { get; set; }
        public string Remarks { get; set; }
        public string LUser { get; set; }
        public Nullable<System.DateTime> LDate { get; set; }
        public string LIP { get; set; }
        public string LMAC { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string CompanyCode { get; set; }
        public string HeightUnit { get; set; }
        public string WeightUnit { get; set; }
    }
}
