//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_JobResponsibilities
    {
        public decimal JobResponsibilitiesCode { get; set; }
        public string JobResponsibilitiesId { get; set; }
        public string EmployeeID { get; set; }
        public string CoWorker { get; set; }
        public string JobObjective { get; set; }
        public string KeyPerformanceAreas { get; set; }
        public string Duties { get; set; }
        public string SupervisorId { get; set; }
        public System.DateTime WEF { get; set; }
        public string Remark { get; set; }
        public string LUser { get; set; }
        public Nullable<System.DateTime> LDate { get; set; }
        public string LIP { get; set; }
        public string LMAC { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string CompanyCode { get; set; }
    }
}
