//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_Attd_JobCardMonthlyData
    {
        public decimal AutoId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string FingerPrintID { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string ProcessType { get; set; }
        public string MonthName { get; set; }
        public Nullable<int> YearName { get; set; }
        public string IsSalApp { get; set; }
        public Nullable<System.DateTime> SalAppDate { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    }
}
