//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_ATD_LeaveType
    {
        public decimal LeaveTypeCode { get; set; }
        public string LeaveTypeId { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string RulePolicy { get; set; }
        public decimal NoOfDay { get; set; }
        public decimal For { get; set; }
        public string YMWD { get; set; }
        public System.DateTime WEF { get; set; }
        public string LUser { get; set; }
        public Nullable<System.DateTime> LDate { get; set; }
        public string LIP { get; set; }
        public string LMAC { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    }
}
