//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_Attd_TimeCalBetweenInOutTime_2
    {
        public decimal autoId { get; set; }
        public string FingerPrintID { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime In { get; set; }
        public System.DateTime Out { get; set; }
        public Nullable<System.TimeSpan> TotalHours { get; set; }
    }
}
