//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_PAY_Rules
    {
        public string RuleName { get; set; }
        public string SHName { get; set; }
        public string RuleDefinition { get; set; }
        public string StateStatus { get; set; }
        public string StateRemarks { get; set; }
    }
}
