//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_Attd_InOutData1
    {
        public decimal autoId { get; set; }
        public string FingerPrintID { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime InTime { get; set; }
        public System.DateTime OutTime { get; set; }
        public string AttdDataType { get; set; }
        public string FileName { get; set; }
    }
}
