//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_Increment
    {
        public decimal TC { get; set; }
        public string IncrementId { get; set; }
        public string EmployeeID { get; set; }
        public string Year { get; set; }
        public decimal PreviousSalary { get; set; }
        public decimal IncAmount { get; set; }
        public decimal PresentSalary { get; set; }
        public System.DateTime WEF { get; set; }
        public string IncLetterNo { get; set; }
        public System.DateTime IncLetterDate { get; set; }
        public string Remark { get; set; }
        public string LUser { get; set; }
        public Nullable<System.DateTime> LDate { get; set; }
        public string LIP { get; set; }
        public string LMAC { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string CompanyCode { get; set; }
        public string IncType { get; set; }
        public string MonthName { get; set; }
    }
}
