//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_Attd_ProcessAttdLog
    {
        public decimal TC { get; set; }
        public string AttdLogHistoryID { get; set; }
        public string AttdProcessType { get; set; }
        public string MachineId { get; set; }
        public string MachineIP { get; set; }
        public Nullable<int> Port { get; set; }
        public System.DateTime DownloadDate { get; set; }
        public System.DateTime DownloadTime { get; set; }
        public Nullable<int> DownloadRecordCount { get; set; }
        public string AttdProcessStatus { get; set; }
        public string LUser { get; set; }
        public Nullable<System.DateTime> LDate { get; set; }
        public string LIP { get; set; }
        public string LMAC { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string CompanyCode { get; set; }
    }
}
