//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_SendEmailEmployeeInfo
    {
        public decimal TC { get; set; }
        public string EmployeeID { get; set; }
        public string TrainingTitleID { get; set; }
        public string TrainingEmial { get; set; }
        public Nullable<System.DateTime> TrainingStartDate { get; set; }
        public Nullable<System.DateTime> TrainingEndDate { get; set; }
        public Nullable<System.DateTime> SubmissionDate { get; set; }
        public string ISMailSend { get; set; }
        public Nullable<System.DateTime> LDate { get; set; }
        public string LUser { get; set; }
        public string LIP { get; set; }
        public string LMAC { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string UserEmployeeID { get; set; }
        public string CompanyCode { get; set; }
    }
}
