//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_EmployeeContactInfo
    {
        public decimal autoId { get; set; }
        public string EmployeeID { get; set; }
        public string ParmanentAddress { get; set; }
        public string ParmanentPostOffice { get; set; }
        public string ParmanentThana { get; set; }
        public string ParmanentPostCode { get; set; }
        public string ParmanentDistrict { get; set; }
        public string ParmanentPhone { get; set; }
        public string PresentAddress { get; set; }
        public string PresentPostOffice { get; set; }
        public string PresentThana { get; set; }
        public string PresentPostCode { get; set; }
        public string PresentDistrict { get; set; }
        public string PresentMobile { get; set; }
        public string PresentPhone { get; set; }
        public string PresentFax { get; set; }
        public string PresentEmail { get; set; }
        public string EmContactName1 { get; set; }
        public string EmContactRelation1 { get; set; }
        public string EmContactAddress1 { get; set; }
        public string EmContactPhone1 { get; set; }
        public string EmContactMobile1 { get; set; }
        public string EmContactFax1 { get; set; }
        public string EmContactEmail { get; set; }
        public string EmContactName2 { get; set; }
        public string EmContactRelation2 { get; set; }
        public string EmContactAddress2 { get; set; }
        public string EmContactPhone2 { get; set; }
        public string EmContactMobile2 { get; set; }
        public string EmContactFax2 { get; set; }
        public string EmContactEmai2 { get; set; }
        public string LUser { get; set; }
        public Nullable<System.DateTime> LDate { get; set; }
        public string LIP { get; set; }
        public string LMAC { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string CompanyCode { get; set; }
        public string UserInfoEmployeeID { get; set; }
        public string ParmanentAddressBangla { get; set; }
        public string PresentAddressBangla { get; set; }
    }
}
