//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_EmployeeAdditionalInfo
    {
        public decimal autoId { get; set; }
        public string EmployeeID { get; set; }
        public string PassportNo { get; set; }
        public string PassportPlaceOfIssue { get; set; }
        public Nullable<System.DateTime> PassportIssueDate { get; set; }
        public Nullable<System.DateTime> PassportExpiryDate { get; set; }
        public string SalaryBankID { get; set; }
        public string SalaryBranchID { get; set; }
        public string BranchAddres { get; set; }
        public string BankACName { get; set; }
        public string BankAcNO { get; set; }
        public string AtmCardNo { get; set; }
        public string LicenseNo { get; set; }
        public string LicenseType { get; set; }
        public Nullable<System.DateTime> LicenseIssueDate { get; set; }
        public Nullable<System.DateTime> LicenseExpireDate { get; set; }
        public string SymbolOfVehicleClass { get; set; }
        public string LicensePlaceOfIssue { get; set; }
        public string WorkPermitNO { get; set; }
        public string WorkPermitType { get; set; }
        public Nullable<System.DateTime> WpEffectiveDate { get; set; }
        public System.DateTime WpExpireDate { get; set; }
        public string LUser { get; set; }
        public Nullable<System.DateTime> LDate { get; set; }
        public string LIP { get; set; }
        public string LMAC { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string CompanyCode { get; set; }
        public string UserInfoEmployeeID { get; set; }
    }
}
