//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_PAY_SalaryInfoDetails
    {
        public decimal SalaryInfoDetailsCode { get; set; }
        public string SalaryInfoDetailsId { get; set; }
        public string EmployeeID { get; set; }
        public string GradeCode { get; set; }
        public decimal Gross { get; set; }
        public decimal Basic { get; set; }
        public decimal Housing { get; set; }
        public decimal Medical { get; set; }
        public decimal Food { get; set; }
        public decimal Stamp { get; set; }
        public decimal Bonus { get; set; }
        public decimal Conveyance { get; set; }
        public System.DateTime WEF { get; set; }
        public string LUser { get; set; }
        public Nullable<System.DateTime> LDate { get; set; }
        public string LIP { get; set; }
        public string LMAC { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string CompanyCode { get; set; }
    }
}
