//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_EmployeeOfficialInfo_test
    {
        public decimal autoId { get; set; }
        public string EmployeeID { get; set; }
        public string CompanyCode { get; set; }
        public string BranchCode { get; set; }
        public string DivisionCode { get; set; }
        public string DepartmentCode { get; set; }
        public string DesignationCode { get; set; }
        public string EmpTypeCode { get; set; }
        public string GradeCode { get; set; }
        public string EmploymentNatureId { get; set; }
        public decimal GrossSalary { get; set; }
        public string CurrencyCode { get; set; }
        public string PaymentPeriodID { get; set; }
        public string DisbursementMethodId { get; set; }
        public string ShiftCode { get; set; }
        public string EmployeeStatus { get; set; }
        public string ReportingTo { get; set; }
        public string HOD { get; set; }
        public string MobileNo { get; set; }
        public string Email { get; set; }
        public string AppointmentLetterNo { get; set; }
        public Nullable<System.DateTime> AppointmentLetterDate { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public decimal JoiningSalary { get; set; }
        public string ProbationPeriodType { get; set; }
        public string ProbationPeriod { get; set; }
        public Nullable<System.DateTime> ConfirmeDate { get; set; }
        public string LUser { get; set; }
        public Nullable<System.DateTime> LDate { get; set; }
        public string LIP { get; set; }
        public string LMAC { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string CompanyCode_Session { get; set; }
        public string UserInfoEmployeeID { get; set; }
        public string StepNoId { get; set; }
        public string TecnicalSkillTypeID { get; set; }
        public string SalaryScaleID { get; set; }
        public Nullable<System.DateTime> ContractEndDate { get; set; }
        public string SectionCode { get; set; }
        public string LineCode { get; set; }
        public string AttendenceID { get; set; }
    }
}
