//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_EmployeeNomineeInfo
    {
        public decimal autoId { get; set; }
        public string EmpNomineeID { get; set; }
        public string EmployeeID { get; set; }
        public string NomineeName { get; set; }
        public string NomineeType { get; set; }
        public string RelationID { get; set; }
        public string PresentAddress { get; set; }
        public string ParmanentAddress { get; set; }
        public Nullable<decimal> ShareParcentage { get; set; }
        public string LUser { get; set; }
        public Nullable<System.DateTime> LDate { get; set; }
        public string LIP { get; set; }
        public string LMAC { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string CompanyCode { get; set; }
        public string UserInfoEmployeeID { get; set; }
    }
}
