//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_Employee_Test
    {
        public decimal autoId { get; set; }
        public string EmployeeID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public Nullable<System.DateTime> DateOfBirthCertificate { get; set; }
        public Nullable<System.DateTime> DateOfBirthOrginal { get; set; }
        public string BirthCertificateNo { get; set; }
        public string PlaceOfBirth { get; set; }
        public string SexCode { get; set; }
        public string BloodGroupCode { get; set; }
        public string NationalityCode { get; set; }
        public string NationalIDNO { get; set; }
        public string ReligionCode { get; set; }
        public string MaritalStatusCode { get; set; }
        public Nullable<System.DateTime> MarriageDate { get; set; }
        public string NoOfSon { get; set; }
        public string NoOfDaughters { get; set; }
        public string CardNo { get; set; }
        public string LUser { get; set; }
        public Nullable<System.DateTime> LDate { get; set; }
        public string LIP { get; set; }
        public string LMAC { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string CompanyCode { get; set; }
        public string UserInfoEmployeeID { get; set; }
        public string PersonalEmail { get; set; }
        public string Telephone { get; set; }
        public string TinNo { get; set; }
        public string ExtraCurriActivities { get; set; }
        public string Remarks { get; set; }
        public string FirstNameBangla { get; set; }
        public string LastNameBangla { get; set; }
        public string PhotoUrl { get; set; }
    }
}
