//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_PAY_Month
    {
        public byte MonthId { get; set; }
        public string MonthName { get; set; }
        public byte MonthNum { get; set; }
        public string MonthName_Bangla { get; set; }
    }
}
