//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_EmployeeQualification
    {
        public decimal autoId { get; set; }
        public string EmpQualificationID { get; set; }
        public string EmployeeID { get; set; }
        public string CourseCode { get; set; }
        public string CourseTitleCode { get; set; }
        public string InstitueCode { get; set; }
        public string Instituteaddress { get; set; }
        public string ResultDivision { get; set; }
        public string YearofPasssing { get; set; }
        public string Dueration { get; set; }
        public string DuratioinType { get; set; }
        public string Achievment { get; set; }
        public string Remarks { get; set; }
        public string LUser { get; set; }
        public Nullable<System.DateTime> LDate { get; set; }
        public string LIP { get; set; }
        public string LMAC { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string CompanyCode { get; set; }
        public string UserInfoEmployeeID { get; set; }
    }
}
