//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_EmployeeMonthlyMovementInfoDetailsExistingCustomerTemp
    {
        public decimal autoId { get; set; }
        public string MMPDetailsID { get; set; }
        public string MMPID { get; set; }
        public Nullable<System.DateTime> PlaningDate { get; set; }
        public string CustomerID { get; set; }
        public string VisitParticuler { get; set; }
        public string AreaID { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public string UserInfoEmployeeID { get; set; }
    }
}
