//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_PAY_AdvancePay
    {
        public decimal AdvancePayCode { get; set; }
        public string AdvancePayId { get; set; }
        public string EmployeeID { get; set; }
        public string AdvanceAdjustStatus { get; set; }
        public decimal AdvanceAmount { get; set; }
        public decimal MonthlyDeduction { get; set; }
        public string SalaryMonth { get; set; }
        public string SalaryYear { get; set; }
        public string NoOfPaymentInstallment { get; set; }
        public string PayHeadNameId { get; set; }
        public string Remark { get; set; }
        public string LUser { get; set; }
        public Nullable<System.DateTime> LDate { get; set; }
        public string LIP { get; set; }
        public string LMAC { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string CompanyCode { get; set; }
    }
}
