//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_PAY_GradePayScale
    {
        public decimal GradePayScaleCode { get; set; }
        public string GradePayScaleId { get; set; }
        public string ScaleType { get; set; }
        public string GradeNameId { get; set; }
        public decimal GradeAmount { get; set; }
        public decimal GraIncAmountPerYear { get; set; }
        public string MaxUpto { get; set; }
        public string YM { get; set; }
        public System.DateTime WEF { get; set; }
        public string LUser { get; set; }
        public Nullable<System.DateTime> LDate { get; set; }
        public string LIP { get; set; }
        public string LMAC { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    }
}
