//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_Pay_Temp_OvertimeSheet
    {
        public decimal AutoId { get; set; }
        public string DepartmentName { get; set; }
        public string SectionName { get; set; }
        public string DepartmentCode { get; set; }
        public string SectionCode { get; set; }
        public string EmployeeID { get; set; }
        public Nullable<decimal> GrossSalary { get; set; }
        public Nullable<int> ActOT { get; set; }
        public Nullable<decimal> OT_Amt { get; set; }
        public Nullable<int> TDay { get; set; }
        public Nullable<decimal> Tiffin { get; set; }
        public Nullable<int> AllowDay { get; set; }
        public Nullable<decimal> AllowAmt { get; set; }
        public Nullable<int> Mobile { get; set; }
        public Nullable<decimal> Total { get; set; }
    }
}
