//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_EIS_Reposition
    {
        public decimal TC { get; set; }
        public string RepositionId { get; set; }
        public string EmployeeID { get; set; }
        public string Type { get; set; }
        public string Year { get; set; }
        public System.DateTime WEF { get; set; }
        public string RefLetterNo { get; set; }
        public System.DateTime RefLetterDate { get; set; }
        public string Remark { get; set; }
        public string PreCompanyCode2 { get; set; }
        public string PreBranchCode { get; set; }
        public string PreDivisionCode { get; set; }
        public string PreDepartmentCode { get; set; }
        public string PreSectionCode { get; set; }
        public string PreLineCode { get; set; }
        public string PreDesignationCode { get; set; }
        public string PreLocationCode { get; set; }
        public string CurrCompanyCode2 { get; set; }
        public string CurrBranchCode { get; set; }
        public string CurrDivisionCode { get; set; }
        public string CurrDepartmentCode { get; set; }
        public string CurrSectionCode { get; set; }
        public string CurrLineCode { get; set; }
        public string CurrDesignationCode { get; set; }
        public string CurrLocationCode { get; set; }
        public string LUser { get; set; }
        public Nullable<System.DateTime> LDate { get; set; }
        public string LIP { get; set; }
        public string LMAC { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string CompanyCode { get; set; }
    }
}
