//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_Pay_Temp_MonthlyReport_NG_5
    {
        public decimal AutoId { get; set; }
        public string EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string DepartmentName { get; set; }
        public string SectionName { get; set; }
        public string LineName { get; set; }
        public string DesignationName { get; set; }
        public string DepartmentCode { get; set; }
        public string SectionCode { get; set; }
        public string LineCode { get; set; }
        public string DesignationCode { get; set; }
        public string GradeName { get; set; }
        public string EmpType { get; set; }
        public Nullable<int> Present { get; set; }
        public Nullable<int> Absent { get; set; }
        public Nullable<int> OT { get; set; }
        public Nullable<int> ActOT { get; set; }
        public Nullable<int> EL { get; set; }
        public Nullable<int> CL { get; set; }
        public Nullable<int> SL { get; set; }
        public Nullable<int> ML { get; set; }
        public Nullable<int> OL { get; set; }
        public Nullable<int> WH { get; set; }
        public string MonthName { get; set; }
        public Nullable<int> YearName { get; set; }
        public string Ex_String_1 { get; set; }
        public string Ex_String_2 { get; set; }
        public string Ex_String_3 { get; set; }
        public Nullable<int> EInt_1 { get; set; }
        public Nullable<int> EInt_2 { get; set; }
        public Nullable<int> EInt_3 { get; set; }
        public Nullable<System.DateTime> EDate_1 { get; set; }
        public Nullable<System.DateTime> EDate_2 { get; set; }
        public Nullable<int> Late { get; set; }
        public string IsSalApp { get; set; }
        public Nullable<System.DateTime> SalAppDate { get; set; }
        public string ProcessType { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Details { get; set; }
        public string ProcessId { get; set; }
        public string ApprovalId { get; set; }
        public string LUser { get; set; }
        public Nullable<System.DateTime> LDate { get; set; }
        public string LIP { get; set; }
        public string LMAC { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string CompanyCode { get; set; }
    }
}
