//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_Pay_Temp__SST_2
    {
        public decimal AutoId { get; set; }
        public string DepartmentName { get; set; }
        public string SectionName { get; set; }
        public string DepartmentCode { get; set; }
        public string SectionCode { get; set; }
        public string EmployeeID { get; set; }
        public Nullable<decimal> GrossSalary { get; set; }
        public Nullable<int> AttendBonus { get; set; }
        public Nullable<decimal> OT_Amt { get; set; }
        public Nullable<decimal> NetPay { get; set; }
    }
}
