//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_Job_Responsibilities
    {
        public decimal autoId { get; set; }
        public string JobResponsibilitiesID { get; set; }
        public string EmployeeID { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public string ISSupervisor { get; set; }
        public string JobObjectives { get; set; }
        public string KeyPerformanceAreas { get; set; }
        public string Duties { get; set; }
        public string ReportingTo { get; set; }
        public Nullable<System.DateTime> WEF { get; set; }
        public string Remarks { get; set; }
        public string LUser { get; set; }
        public Nullable<System.DateTime> LDate { get; set; }
        public string LIP { get; set; }
        public string LMAC { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string CompanyCode { get; set; }
        public string UserInfoEmployeeID { get; set; }
    }
}
