//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_EmployeeTraining
    {
        public decimal autoId { get; set; }
        public string EmpTriCode { get; set; }
        public string EmployeeCode { get; set; }
        public string TrainingTitleCode { get; set; }
        public string InstituteName { get; set; }
        public string YearsOfCompletion { get; set; }
        public string Duration { get; set; }
        public string Achivement { get; set; }
        public string Remarks { get; set; }
        public string LUser { get; set; }
        public Nullable<System.DateTime> LDate { get; set; }
        public string LIP { get; set; }
        public string LMAC { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string CompanyCode { get; set; }
    }
}
