//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_Attd_JobCard_WeeklyHoliday
    {
        public decimal AutoId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string InTime { get; set; }
        public string OutTime { get; set; }
        public string Late { get; set; }
        public string OT { get; set; }
        public string AttStatus { get; set; }
        public string OTTimeBr { get; set; }
        public string OTTimeAct { get; set; }
    }
}
