//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_Def_Section
    {
        public decimal autoId { get; set; }
        public string SectionCode { get; set; }
        public string SectionName { get; set; }
        public string SectionShortName { get; set; }
        public string LUser { get; set; }
        public Nullable<System.DateTime> LDate { get; set; }
        public string LIP { get; set; }
        public string LMAC { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string BanglaSection { get; set; }
        public string BanglaShortName { get; set; }
        public string DepartmentCode { get; set; }
    }
}
