//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_Def_BankAndNomineeInfo
    {
        public decimal AutoId { get; set; }
        public string BankAndNomineeId { get; set; }
        public string EmployeeID { get; set; }
        public string BankID { get; set; }
        public string BankBranchID { get; set; }
        public string BankAccountName { get; set; }
        public string BankAccountNo { get; set; }
        public string ATMCardNo { get; set; }
        public string NomineeName { get; set; }
        public string Relation { get; set; }
        public string PresentAddress { get; set; }
        public string ParmanentAddress_ { get; set; }
        public string LUser { get; set; }
        public Nullable<System.DateTime> LDate { get; set; }
        public string LIP { get; set; }
        public string LMAC { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string CompanyCode { get; set; }
        public string EmployeeID2 { get; set; }
    }
}
