//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_ATD_CompanyLeaveSetup
    {
        public decimal CompLeaveSetupCode { get; set; }
        public string CompLeaveSetupId { get; set; }
        public string LeaveTypeId { get; set; }
        public string EmployeeID { get; set; }
        public decimal NoOfDay { get; set; }
        public string Year { get; set; }
        public string LUser { get; set; }
        public Nullable<System.DateTime> LDate { get; set; }
        public string LIP { get; set; }
        public string LMAC { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    }
}
