//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_EmployeeMembership
    {
        public decimal autoId { get; set; }
        public string EmpMembershipCode { get; set; }
        public string EmployeeCode { get; set; }
        public string Organization { get; set; }
        public string Address { get; set; }
        public string MemberId { get; set; }
        public string Position { get; set; }
        public System.DateTime JoinDate { get; set; }
        public Nullable<System.DateTime> Expires { get; set; }
        public string Remarks { get; set; }
        public string LUser { get; set; }
        public Nullable<System.DateTime> LDate { get; set; }
        public string LIP { get; set; }
        public string LMAC { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string CompanyCode { get; set; }
    }
}
