//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_Pay_Temp_Bonus2
    {
        public decimal AutoId { get; set; }
        public string EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string DepartmentName { get; set; }
        public string SectionName { get; set; }
        public string LineName { get; set; }
        public string DesignationName { get; set; }
        public string DepartmentCode { get; set; }
        public string SectionCode { get; set; }
        public string LineCode { get; set; }
        public string DesignationCode { get; set; }
        public string JoiningDate { get; set; }
        public string GradeName { get; set; }
        public string EmpType { get; set; }
        public Nullable<decimal> GrossSalary { get; set; }
        public Nullable<int> T_Month { get; set; }
        public Nullable<decimal> percentage { get; set; }
        public Nullable<decimal> Bonus { get; set; }
        public string MonthName { get; set; }
        public Nullable<int> YearName { get; set; }
    }
}
