//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_ShortLeaveHoursMonthWise
    {
        public decimal autoId { get; set; }
        public string EmployeeId { get; set; }
        public Nullable<System.DateTime> MonthStartDate { get; set; }
        public Nullable<System.DateTime> MonthEndDate { get; set; }
        public string TotalTime { get; set; }
        public Nullable<decimal> TotalHours { get; set; }
        public Nullable<int> IsSLTimeAdj { get; set; }
    }
}
