//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_WorkingDayDeclaredEmployeeInfo
    {
        public decimal autoId { get; set; }
        public string EmployeeID { get; set; }
        public string DepartmentCode { get; set; }
        public System.DateTime WorkingDayDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string MonthName { get; set; }
        public Nullable<int> YearName { get; set; }
    }
}
