//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_ATD_Shift
    {
        public decimal autoId { get; set; }
        public string ShiftCode { get; set; }
        public string ShiftName { get; set; }
        public string ShiftShortName { get; set; }
        public System.DateTime ShiftStartTime { get; set; }
        public System.DateTime ShiftEndTime { get; set; }
        public System.DateTime LateTime { get; set; }
        public System.DateTime AbsentTime { get; set; }
        public System.DateTime WEF { get; set; }
        public string Remarks { get; set; }
        public string LUser { get; set; }
        public Nullable<System.DateTime> LDate { get; set; }
        public string LIP { get; set; }
        public string LMAC { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ShiftTypeID { get; set; }
    }
}
