//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_WorkingDaySectionWiseDec
    {
        public decimal autoId { get; set; }
        public string WDSWD_ID { get; set; }
        public string DepartmentCode { get; set; }
        public string WorkingDayCode { get; set; }
        public System.DateTime WorkingDayDate { get; set; }
    }
}
