//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_PAY_Transfer
    {
        public decimal TransferCode { get; set; }
        public string TransferId { get; set; }
        public string EmployeeID { get; set; }
        public string OldCompanyCode { get; set; }
        public string OldBranchCode { get; set; }
        public string OldDivisionCode { get; set; }
        public string OldDepartmentCode { get; set; }
        public string OldSectionCode { get; set; }
        public string OldLineCode { get; set; }
        public string OldEmpTypeCode { get; set; }
        public string OldDesignationCode { get; set; }
        public string OldsupervisorAutoId { get; set; }
        public string CompanyCode { get; set; }
        public string BranchCode { get; set; }
        public string DivisionCode { get; set; }
        public string DepartmentCode { get; set; }
        public string SectionCode { get; set; }
        public string LineCode { get; set; }
        public string EmpTypeCode { get; set; }
        public string DesignationCode { get; set; }
        public string supervisorAutoId { get; set; }
        public System.DateTime WEF { get; set; }
        public string Remark { get; set; }
        public string LUser { get; set; }
        public Nullable<System.DateTime> LDate { get; set; }
        public string LIP { get; set; }
        public string LMAC { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    }
}
