//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_Def_Grade
    {
        public decimal autoId { get; set; }
        public string GradeCode { get; set; }
        public string GradeName { get; set; }
        public string GradeShortName { get; set; }
        public Nullable<decimal> FromGrossSalary { get; set; }
        public Nullable<decimal> ToGrossSalary { get; set; }
        public string EmpTypeCode { get; set; }
        public string LUser { get; set; }
        public Nullable<System.DateTime> LDate { get; set; }
        public string LIP { get; set; }
        public string LMAC { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    }
}
