//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_NomineeSignature
    {
        public int autoId { get; set; }
        public string EmployeeID { get; set; }
        public string NomineeID { get; set; }
        public byte[] Photo { get; set; }
        public string ImgType { get; set; }
        public long ImgSize { get; set; }
    }
}
