//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_ManualTimeScheduleEntry
    {
        public decimal AutoId { get; set; }
        public string MTS_ID { get; set; }
        public string EmployeeID { get; set; }
        public string WorkingOrOffDay { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<System.DateTime> OfficeInTime { get; set; }
        public Nullable<System.DateTime> OfficeOutTime { get; set; }
        public string Remarks { get; set; }
        public string LUser { get; set; }
        public Nullable<System.DateTime> LDate { get; set; }
        public string LIP { get; set; }
        public string LMAC { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string CompanyCode { get; set; }
        public string SessionEmployeeID { get; set; }
        public string RSS_ID { get; set; }
    }
}
