//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_Temp_JobCard_3
    {
        public decimal AutoId { get; set; }
        public string EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string DesignationName { get; set; }
        public string DepartmentName { get; set; }
        public string LineName { get; set; }
        public string Date { get; set; }
        public string InTime { get; set; }
        public string OutTime { get; set; }
        public string AttStatus { get; set; }
        public Nullable<System.DateTime> SDIntime { get; set; }
        public Nullable<System.DateTime> ConInTime { get; set; }
        public Nullable<System.DateTime> SDOutTime { get; set; }
        public Nullable<System.DateTime> AbsentTime { get; set; }
        public Nullable<System.DateTime> MinTime { get; set; }
        public Nullable<System.DateTime> MaxTime { get; set; }
        public Nullable<System.DateTime> AccDate { get; set; }
    }
}
