//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_Def_PortInfo
    {
        public int AutoId { get; set; }
        public string PortId { get; set; }
        public string PortName { get; set; }
        public string ShortName { get; set; }
        public string DeliveryMethodId { get; set; }
        public string PortAddress { get; set; }
        public string CountryID { get; set; }
        public string LUser { get; set; }
        public Nullable<System.DateTime> LDate { get; set; }
        public string LIP { get; set; }
        public string LMAC { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string EmployeeID { get; set; }
        public string CompanyCode { get; set; }
    }
}
