//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_Def_Gatepass
    {
        public decimal AutoId { get; set; }
        public string Gatepass_NO { get; set; }
        public string GatePassType { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string VehicleRegNo { get; set; }
        public string InvoiceNO { get; set; }
        public string ChallanNo { get; set; }
        public string RepairStatus { get; set; }
        public string Returned { get; set; }
        public string AllowTo { get; set; }
        public string AllowAddress { get; set; }
        public string AllowPhone { get; set; }
        public string allowNationalID { get; set; }
        public string Gate_Keeper { get; set; }
        public string SecurityInCharge { get; set; }
        public string StoreOfficer { get; set; }
        public string StoreOfficerPhone { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string LUser { get; set; }
        public Nullable<System.DateTime> LDate { get; set; }
        public string LIP { get; set; }
        public string LMAC { get; set; }
        public string CompanyID { get; set; }
        public string UserEmployeeID { get; set; }
        public string JobCardNo { get; set; }
        public string ApproveStatus { get; set; }
        public string ApproveRemarks { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public string VehicleInChargeID { get; set; }
        public string VehicleInChargePhone { get; set; }
    }
}
