//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_Def_GatepassDetails
    {
        public decimal AutoId { get; set; }
        public string Gatepass_NO { get; set; }
        public string ItemID { get; set; }
        public string Discription { get; set; }
        public Nullable<decimal> itemQuantity { get; set; }
        public string quantityUnit { get; set; }
        public string Packing { get; set; }
        public string Remarks { get; set; }
        public string UseremployeeID { get; set; }
    }
}
