//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlyEmpInfoData
    {
        public decimal AutoId { get; set; }
        public string EmployeeID { get; set; }
        public string CompanyCode { get; set; }
        public string BranchCode { get; set; }
        public string DepartmentCode { get; set; }
        public string SectionCode { get; set; }
        public string LineCode { get; set; }
        public string DesignationCode { get; set; }
        public string GradeCode { get; set; }
        public string EmpTypeCode { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public Nullable<decimal> GrossSalary { get; set; }
        public Nullable<decimal> Medical { get; set; }
        public Nullable<decimal> Conveyance { get; set; }
        public Nullable<decimal> Food { get; set; }
        public Nullable<int> Present { get; set; }
        public Nullable<int> Late { get; set; }
        public Nullable<int> Absent { get; set; }
        public Nullable<int> Weekend { get; set; }
        public Nullable<int> Holiday { get; set; }
        public Nullable<decimal> CL { get; set; }
        public Nullable<decimal> ML { get; set; }
        public Nullable<int> EL { get; set; }
        public Nullable<decimal> OT { get; set; }
        public Nullable<decimal> ActOT { get; set; }
        public Nullable<int> AttendBonus { get; set; }
        public string MonthName { get; set; }
        public Nullable<int> YearName { get; set; }
        public string IsSalApp { get; set; }
        public Nullable<System.DateTime> SalAppDate { get; set; }
        public string ProcessType { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Details { get; set; }
        public string ProcessId { get; set; }
        public string ApprovalId { get; set; }
        public string LUser { get; set; }
        public Nullable<System.DateTime> LDate { get; set; }
        public string LIP { get; set; }
        public string LMAC { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    }
}
