//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class RMG_Prod_Def_NegativeFormat
    {
        public int TC { get; set; }
        public string DecimalPlaces { get; set; }
        public string NegativeFormat { get; set; }
    }
}
