//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_SupplierBankAccount
    {
        public decimal AutoId { get; set; }
        public string SBAID { get; set; }
        public string SupplierID { get; set; }
        public string BankID { get; set; }
        public string BankBranchID { get; set; }
        public string AccountName { get; set; }
        public string LUser { get; set; }
    }
}
