//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_Def_BankBranchInfo
    {
        public int TC { get; set; }
        public string BankBranchID { get; set; }
        public string BankBranchName { get; set; }
        public string ShortName { get; set; }
        public string BankID { get; set; }
        public string SWIFTCode { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> LDate { get; set; }
        public string LUser { get; set; }
        public string LIP { get; set; }
        public string LMAC { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    }
}
