//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ReportFormat
    {
        public decimal Id { get; set; }
        public string formatID { get; set; }
        public string formatName { get; set; }
        public Nullable<System.DateTime> entryDate { get; set; }
        public Nullable<System.DateTime> modifyDate { get; set; }
    }
}
