//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tem_AttdSummary2
    {
        public decimal AutoId { get; set; }
        public string DepartmentCode { get; set; }
        public string DepartmentName { get; set; }
        public int Strength { get; set; }
        public int DeviceAccessedEmployee { get; set; }
        public int Present { get; set; }
        public int Late { get; set; }
        public int Absent { get; set; }
        public int Leave { get; set; }
    }
}
