//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_T_DashboardTimeSum_LS
    {
        public decimal autoId { get; set; }
        public string EmployeeID { get; set; }
        public string TotalHours { get; set; }
        public Nullable<decimal> TotHrswith_WH { get; set; }
        public Nullable<decimal> TotAvgHrs { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    }
}
