//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_HRM_DiagnosticTestDetails
    {
        public decimal autoId { get; set; }
        public string TestID { get; set; }
        public string DiagnosticTestNo { get; set; }
        public string ServiceChageID { get; set; }
        public string TechnicianID { get; set; }
        public string UserInfoEmployeeID { get; set; }
    }
}
