//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temtb_Att_JobCard_2
    {
        public decimal AutoId { get; set; }
        public string FingerPrintID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> MinTime { get; set; }
        public Nullable<System.DateTime> MaxTime { get; set; }
        public string MachineId { get; set; }
    }
}
